# Sample configuration file for training a 3D U-Net on a task of predicting the nuclei in 3D stack from the lightsheet
# microscope. Training done with Binary Cross-Entropy.
# Training and validation data can be downloaded from: https://osf.io/thxzn/

#BH
trainer:
  # mode train or test 
  mode: "test"
  # gpu number 
  gpu_idx: 0
  # path to the checkpoint directory
  checkpoint_dir: "/home/bh/PycharmProjects/3d_pytorch_bh/data"
  # path to latest checkpoint; if provided the training will be resumed from that checkpoint
  resume: False
  save_model_path: "/home/bh/PycharmProjects/3d_pytorch_bh/pretrained/"
  save_model_name: "3d_deepAAA_50"
  # max number of epochs
  max_epochs: 121
  # how many iterations between validations
  validate_after_iters: 20
  # model with higher eval score is considered better
  eval_score_higher_is_better: True
  

loss:
  # use BCE loss 
  # name: BCEWithLogitsLoss # network + sigmoid
  name: dice

# optimizer configuration
optimizer:
  # initial learning rate
  lr: 0.0001
  # weight decay
  weight_decay: 0.00001
 
aaa:
  # batch dimension; if number of GPUs is N > 1, then a batch_size of N * batch_size will automatically be taken for DataParallel
  batch_size: 6
  # how many subprocesses to use for data loading
  num_workers: 12

  file_path: "/home/bh/PycharmProjects/3d_pytorch_bh/data/"
  prepro_path: "/home/bh/PycharmProjects/3d_pytorch_bh/data/preprocess/" 
  validation_path: "/home/bh/PycharmProjects/3d_pytorch_bh/visualization/"
  raw_path: "raw_256_50"
  mask_path: "mask_256_50"
  raw_test_path: "raw_256_50_test"
  mask_test_path: "mask_256_50_test"
  weight_path: null

  # threshold number of slice in datasets
  slice_num: 8
  valid_ratio: 0.1


  # configuration of the train loader
  train:
    transformer:
      raw:
        # subtract mean and divide by std dev
        # - name: Standardize
        - name: RandomFlip
        - name: RandomRotate90
        - name: RandomRotate
          # rotate only in ZY plane due to anisotropy
          axes: [ [ 2, 1 ] ]
          # rotates by choosing random angle from [-30, 30] deg
          angle_spectrum: 30
          mode: reflect
        - name: ElasticDeformation
          spline_order: 3
        - name: ToTensor
          expand_dims: true

      label:
        - name: RandomFlip
        - name: RandomRotate90
        - name: RandomRotate
          # rotate only in ZY plane due to anisotropy
          axes: [ [ 2, 1 ] ]
          angle_spectrum: 30
          mode: reflect
        - name: ElasticDeformation
          spline_order: 0
          # convert target volume to binary mask
        - name: BlobsToMask
          # append ground truth labels in the last channel of the target for evaluation metric computation
          append_label: true
          # if 'true' appends boundary mask as a 2nd channel of the target; boundaries are computed using the 'find_boundaries()' function from skimage
          # learning the boundaries as a 2nd objective sometimes helps with the nuclei mask prediction
          boundary: false
        - name: ToTensor
          expand_dims: false




